### ISSUE TITLE
Ponteiro de pastas

### ISSUE THREAD

**Issue by ViniciusHass** [Treinamento-Stefa-IA-DevOps/treinamento-dia-04-08-MaksonViini#1]
https://github.com/Treinamento-Stefa-IA-DevOps/treinamento-dia-04-08-MaksonViini/blob/9461273547d3579ddb6876a6791bd17cc2a0ed4d/tarefa/Dockerfile#L12

Boa Tarde  @MaksonViini **Makson**,

O seu ponteiro esta apontando para a pasta codigo quando inicia o programa, e você esta tentando ler de lá o arquivo Titanic, da uma revisda nisso

**Comment by MaksonViini** [comment]
Consertado, tinha colocado assim pq estava testando a partir da pasta tarefa, precisava passar o diretorio completo
